### ISSUE TITLE
Add lib folder to this project which guarantees building

### ISSUE THREAD

**Issue by maxgerhardt** [atomic14/tensorflow-lite-esp32#2]
Per https://github.com/atomic14/platformio-tensorflow-lite/issues/3.

The project should include the `lib/tfmicro` folder used during the tutorial which ensures a good build.

**Comment by cgreening** [comment]
I'll do this now.

**Comment by cgreening** [comment]
af8a1412b68d141e4e0ed88f2cd08ab37f23c2ad
