### ISSUE TITLE
Code didn't upload

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/tensorflow-lite-esp32#6]
![Picsart_22-04-29_18-36-44-829](https://user-images.githubusercontent.com/94418247/165950257-b5354e0e-bcb5-466b-8cb9-9524d4441ab7.jpg)
I was compiled the code then the massage is successful but when i am upload the code it's said upload failed please tell me whats the reason for this please 🥺
![Picsart_22-04-29_18-37-00-081](https://user-images.githubusercontent.com/94418247/165950620-b207f962-03b0-46bf-a988-0fe991213b6c.jpg)

**Comment by cgreening** [comment]
Can you make sure you open the "firmware" folder in VSCode and then do a build and upload?

**Comment by Anugaradhawa** [comment]
Ok i was tried but still it's said failed friend what is the reason you think please tell me please 🥺

**Comment by cgreening** [comment]
Can you expand the terminal window a bit so that the error is visible?

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_18-56-46-221.jpg…]()


Yes but i didn't understand error friend

**Comment by cgreening** [comment]
Try editing `platformio.ini` and remove the two lines:

```
upload_port = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART
```

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_18-56-46-221.jpg…]()

Yes but i didn't understand error friend

**Comment by Anugaradhawa** [comment]
![Picsart_22-04-29_19-02-15-553](https://user-images.githubusercontent.com/94418247/165954445-3d77b877-d399-41f4-b3c3-d292e7db6b8e.jpg)

I was edit it but it doesn't upload please help me please 🙏🥺

**Comment by cgreening** [comment]
So the error is saying that it can't find your device on `/dev/cu.SLAB_USBtoUART`

That's because your device is probably on a different port. So remove the two lines from platform.io and try again and see what error you see.

There's some good instructions here on working out what COM port your device is on when using windows: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html

**Comment by Anugaradhawa** [comment]
![Picsart_22-04-29_19-19-30-696](https://user-images.githubusercontent.com/94418247/165957820-418b000f-d7d9-4c52-a53e-7e577f8e16df.jpg)

Yes you right there was a port error now I install silicon lab driver and then it's recognize it but some time it  recognize it and some time it doesn't recognize it

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_19-23-07-851.jpg…]()

problem tab

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_19-23-55-277.jpg…]()

Problem tab

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_19-44-07-844.jpg…]()

Now another error occur are you know a fix for this

**Comment by Anugaradhawa** [comment]
![Uploading Picsart_22-04-29_19-44-07-844.jpg…]()
Again a problem are you know a fix

**Comment by Anugaradhawa** [comment]
![Picsart_22-04-29_19-54-58-205](https://user-images.githubusercontent.com/94418247/165963868-becc1e10-3a0e-49c5-ad7d-58d6dde0eb7a.jpg)

Finally i fix it thanks a lot friend error is port not selected 🙏🙏🙏 thanks a lot agin friend

**Comment by cgreening** [comment]
That's great! Well done.

**Comment by Anugaradhawa** [comment]
Thanks a lot. please help me in future errors ok friend thankyou
